# Generated by Django 6.0.5 on 2026-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
