# Generated by Django 6.0.5 on 2026-06-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_tache_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('gain_estime', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('propose', 'Propose'), ('en_cours', 'En cours'), ('realise', 'Realise')], default='propose', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaizens', to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Muda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_gaspillage', models.CharField(choices=[('surproduction', 'Surproduction'), ('attente', 'Attente'), ('transport', 'Transport'), ('stock', 'Stock'), ('mouvement', 'Mouvement'), ('defaut', 'Defaut'), ('surtraitement', 'Surtraitement')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('impact', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudas', to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='VSMStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('temps_valeur', models.IntegerField(default=0)),
                ('temps_attente', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=1)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vsm_steps', to='projects.projet')),
            ],
        ),
    ]
